### ISSUE TITLE
Tłumaczenie testu na inną wersję językową.

### ISSUE THREAD

**Issue by Kar0lLasek** [lodz-university-of-technology-masi/TheRowdyruffBoys#33]

**Comment by Bonniu** [comment]
https://tech.yandex.com/translate/doc/dg/reference/translate-docpage/

z tego trzeba korzystac przy tlumaczeniu

**Comment by Kar0lLasek** [comment]
Do 9 stycznia stworzę gotowego jsona przetłumaczonego z EN na PL na stronie tworzenia nowych testów NewTest.html.

- @Bonniu @Mmarcopollo stwórzcie potem wysyłanie tego testu do bazy (do przemyślenia).

_Można też zrobić tłumaczenie odwrotne z PL na EN? 
Albo narzucić że test musi być napisany po angielsku?_

**Comment by Kar0lLasek** [comment]
Zmienna _txt_ w _newTest.js_ zawiera json z przetłumaczonym tekstem do DynamoDB.
124 linijka jest wywołana funkcja redirectToTesty() i po niej jest już gotowa zmienna _txt_.
